spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}

  mvc:
    log-request-details: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dccuxj8ll}
  api-key: ${CLOUDINARY_API_KEY:934946519676845}
  api-secret: ${CLOUDINARY_API_SECRET:JORMLqc5oK1HzEPqS3toNumm5XI}

logging:
  level:
    web: DEBUG
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
